name: Monthly Database Update

on:
  workflow_dispatch:   # Allows manual triggering of the workflow
  schedule:
    - cron: "0 0 1 * *"  # Runs at midnight on the first of every month (UTC)

jobs:
  update-db:
    runs-on: windows-latest  # Switch to Windows runner for Windows Authentication

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyodbc requests

      - name: Run Database Update Script
        env:
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          python refresh.py
